blank_issues_enabled: true
contact_links:
  - name: Jigocoin Security Policy
    url: https://github.com/ancrumar/jigocoin-core/blob/master/SECURITY.md
    about: View security policy

  - name: Jigocoin Core Developers
    url: https://github.com/ancrumar/jigocoin-core
    about: Jigocoin homepage
